library(data.table)
library(dtplyr)
library(tidyverse)
library(reshape2)
library(gdxrrw)
library(R6)
library(ggthemes)
library(DoE.wrapper)
library(DiceEval)
library(DiceDesign)
library(tables)
booktabs() # enable booktabs style
igdx(gamsPath)
rm(list=ls(all=TRUE))
